services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka

    ports:
      - "9074:9074"

    environment:
      KAFKA_NODE_ID: 1

      KAFKA_PROCESS_ROLES: "broker,controller"

      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@localhost:9093"

      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"

      KAFKA_LISTENERS: "EXTERNAL://0.0.0.0:9074,CONTROLLER://0.0.0.0:9093"

      KAFKA_ADVERTISED_LISTENERS: "EXTERNAL://localhost:9074"

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"

      KAFKA_INTER_BROKER_LISTENER_NAME: "EXTERNAL"

      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"

      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1

      KAFKA_NUM_PARTITIONS: 3

  redis:
    image: redis:7.4
    container_name: omnitrade-redis

    restart: unless-stopped

    ports:
      - "6379:6379"

    command: redis-server --appendonly yes

    volumes:
      - redis-data:/data

volumes:
  redis-data: